# Python Numpy Library for Data Analysis

In [1]:
#Creating a numpy array

import numpy as np
nums_list = [10,12,14,16,20]
nums_array = np.array(nums_list)
type(nums_array)

numpy.ndarray

In [2]:
#Creating a 2d array

row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1,row2,row3])
nums_2d.shape

(3, 3)

In [3]:
#Using Arange to create a array from a range of integers

nums_arr = np.arange(5,11)
print(nums_arr)

[ 5  6  7  8  9 10]


In [5]:
#Using arange with a step

nums_arr = np.arange(5,12,2)
print(nums_arr)

[ 5  7  9 11]


In [6]:
#Using the ones method to create a numpy array of all ones

ones_array = np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


In [8]:
# Creating a 2d array with ones method

ones_array = np.ones((6,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
# USing the eyes method to create am identity matrix in the form of a 2d numpy array

eyes_array = np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
#using the randon.rand method to create a numpy array with uniform distribution
uniform_random = np.random.rand(4,5)
print(uniform_random)

[[0.8768333  0.15487185 0.54035448 0.66353507 0.05943838]
 [0.21417262 0.65069589 0.81861537 0.75335651 0.87580334]
 [0.00107475 0.57381031 0.92991412 0.49514949 0.82087223]
 [0.0326285  0.1828137  0.49092248 0.41967931 0.05985893]]


In [11]:
#Using random.randn to create a numpy array with normal distribution

normal_random = np.random.randn(4,5)
print(normal_random)

[[ 0.39411334  0.96615108  2.19273127  0.94653715 -1.5549027 ]
 [ 0.47444067  0.93133299 -1.27280663 -0.84580118  1.17745444]
 [ 0.44062174 -0.29737306  0.11315902  0.38840717 -0.39550301]
 [-0.93834745  1.64434895  0.4755017  -0.23411907  0.77368131]]


In [12]:
#Using random.randint to create a numpy array with random integers between a certain range 

integer_random = np.random.randint(10,50,5)
print(integer_random)

[42 37 47 31 42]


In [13]:
# Reshaping numpy arrays

uniform_random = np.random.rand(4,6)
print(uniform_random)

uniform_random = uniform_random.reshape(3,8)
print(uniform_random)

[[0.43228957 0.20173321 0.00245277 0.17843294 0.69527384 0.17377727]
 [0.62834706 0.86480264 0.5823614  0.54716118 0.01564637 0.15121573]
 [0.08959949 0.50905337 0.19671275 0.62802556 0.49539717 0.16298515]
 [0.75201159 0.52348445 0.02060294 0.41187949 0.18316224 0.02732851]]
[[0.43228957 0.20173321 0.00245277 0.17843294 0.69527384 0.17377727
  0.62834706 0.86480264]
 [0.5823614  0.54716118 0.01564637 0.15121573 0.08959949 0.50905337
  0.19671275 0.62802556]
 [0.49539717 0.16298515 0.75201159 0.52348445 0.02060294 0.41187949
  0.18316224 0.02732851]]


In [18]:
# Array indexing and Slicing

s = np.arange(1,11)
print(s)

print(s[1])

print(s[1:9])

print(s[:5])
print(s[5:])

#Slicing a 2d numpy array 

row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

print()
nums_2d = np.array([row1,row2,row3])
print(nums_2d[:2,:])

print()

print(nums_2d[:,:2])

print()


print(nums_2d[1:,1:])


[ 1  2  3  4  5  6  7  8  9 10]
2
[2 3 4 5 6 7 8 9]
[1 2 3 4 5]
[ 6  7  8  9 10]

[[10 12 13]
 [45 32 16]]

[[10 12]
 [45 32]
 [45 32]]

[[32 16]
 [32 16]]


# Numpy for Arithmetic Operations

In [19]:
# Finding Square Roots

nums = [10,20,30,40,50]
np_sqr = np.sqrt(nums)
print(np_sqr)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [20]:
# Finding Logs

nums = [10,20,30,40,50]
np_log = np.log(nums)
print(np_log)

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [21]:
#Finding Exponents

nums = [10,20,30,40,50]
np_exp = np.exp(nums)
print(np_exp)

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


In [22]:
# Finding Sine and Cosine
nums = [10,20,30,40,50]
np_sine = np.sin(nums)
print(np_sine)

nums = [10,20,30,40,50]
np_cos = np.cos(nums)
print(np_cos)


[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


# Numpy for Linear Algebra Operations

In [23]:
#Finding Matrix Dot Product

A = np.random.randn(4,5)

B = np.random.randn(5,4)

Z = np.dot(A,B)

print(Z)

[[ 5.88350924e-03 -1.48596222e+00 -2.25259686e+00 -1.57283152e+00]
 [ 1.13976875e+00 -2.74887458e+00  6.27783584e+00 -4.61353514e+00]
 [ 1.81263759e+00  1.03865623e+00  5.45218933e+00 -2.57724751e+00]
 [-1.35633422e-01 -2.08124584e+00  4.15709436e+00 -2.67461015e+00]]


In [24]:
# Element-wise Matrix Multiplication

row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]

nums_2d = np.array([row1,row2,row3])
multiply = np.multiply(nums_2d,nums_2d)
print(multiply)

[[ 100  144  169]
 [2025 1024  256]
 [2025 1024  256]]


In [27]:
# Finding Matrix Inverse

row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]

nums_2d = np.array([row1,row2,row3])
inverse = np.linalg.inv(nums_2d)
print(inverse)

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [28]:
# Finding Matrix Determinant

row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]
nums_2d = np.array([row1,row2,row3])

determinant = np.linalg.det(nums_2d)
print(determinant)

-9.51619735392994e-16


In [29]:
# Finding Matrix Trace

row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]

nums_2d = np.array([row1,row2,row3])

trace = np.trace(nums_2d)
print(trace)


15
